/** Run with Node 24+, PLAYWRIGHT_PATH pointing to an installed Playwright package. Uses an isolated temporary database. */
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { once } from 'node:events';
import { createAppServer } from '../src/server.js';
import { openStore, passwordHash } from '../src/desk/store.js';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
const dir = await mkdtemp(join(tmpdir(), 'citizen-navigation-'));
const dbPath = join(dir, 'fixture.sqlite');
const db = openStore(dbPath);
db.prepare('INSERT INTO users VALUES(?,?,?)').run('navigation-tester', passwordHash('test-password-2026'), 'admin');
const complaint = { id: 1, text: 'Не работает фонарь у школы', address: 'Тестовый адрес, 12', districtId: 'nura', category: 'safety', source: 'demo', status: 'resolved', priority: 'normal', version: 1, createdAt: '2026-01-01T12:00:00Z', updatedAt: '2026-01-03T12:00:00Z', replies: [{ at: '2026-01-03T12:00:00Z', text: 'Работы завершены. Проверьте освещение.' }], history: [], attachments: [] };
db.prepare('INSERT INTO complaints(id,submission,fingerprint,data) VALUES(?,?,?,?)').run(1, 'test-citizen', 'fixture', JSON.stringify(complaint));
db.close();
const server = createAppServer({ deskOptions: { path: dbPath } });
server.listen(0, '127.0.0.1');
await once(server, 'listening');
const origin = `http://127.0.0.1:${server.address().port}`;
const browser = await chromium.launch({ headless: true, channel: process.env.PLAYWRIGHT_CHANNEL || 'chrome' });
const context = await browser.newContext({ viewport: { width: 390, height: 844 }, locale: 'ru-RU' });
const page = await context.newPage();
page.setDefaultTimeout(10000);
const errors = [];
page.on('pageerror', error => errors.push(error.message));
async function visible(selector) { await page.locator(`${selector}:not([hidden])`).waitFor(); }
async function noOverflow() { assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, page.url().split('#')[0]); }
try {
  const login = await context.request.post(origin + '/api/desk/login', { headers: { 'X-Desk-Request': '1' }, data: { login: 'navigation-tester', password: 'test-password-2026' } });
  assert.equal(login.status(), 200);
  const linkResponse = await context.request.post(origin + '/api/desk/resident/complaints/1/link', { headers: { 'X-Desk-Request': '1' }, data: { version: 1 } });
  assert.equal(linkResponse.status(), 201);
  const { token } = await linkResponse.json();
  const requests = [];
  page.on('request', request => requests.push(request.url()));
  await page.goto(origin + '/resident.html');
  await visible('#access-state');
  await page.locator('#access-link').fill('invalid');
  await page.locator('#access-form button').click();
  await visible('#access-error');
  await page.locator('#access-link').fill(`https://unrelated.invalid/resident.html#${token}`);
  await page.locator('#access-form button').click();
  assert.equal(await page.locator('#access-link').getAttribute('aria-invalid'), 'true');
  await page.locator('#access-link').fill(`${origin}/resident.html#${token.toUpperCase()}`);
  await page.locator('#access-form button').click();
  await visible('#complaint-content');
  assert.match(await page.locator('#next-step').innerText(), /результат для проверки/);
  assert.equal(await page.locator('#access-link').inputValue(), '');
  assert.equal(requests.some(url => url.includes(token)), false, 'Bearer token must never appear in network URLs');
  await noOverflow();
  await page.locator('#close-complaint').click();
  await visible('#access-state');
  assert.equal(new URL(page.url()).hash, '');
  await page.locator('#access-link').fill('f'.repeat(64));
  await page.locator('#access-form button').click();
  await page.getByRole('heading', { name: 'Ссылка недоступна', exact: true }).waitFor();
  await page.locator('#access-link').fill(token);
  await page.locator('#access-form button').click();
  await visible('#complaint-content');
  await page.locator('input[value=unresolved]').check();
  await page.locator('#comment').fill('Свет всё ещё не работает.');
  await page.locator('#submit-feedback').click();
  await page.waitForFunction(() => document.getElementById('complaint-status').textContent === 'На рассмотрении');
  assert.equal(await page.locator('#feedback-form').isHidden(), true);
  await page.screenshot({ path: '/tmp/ascension-resident-navigation.png', fullPage: true });
  console.log('PASS resident: entry, rejected foreign URL, revoked link recovery, feedback, close, mobile layout, token secrecy');

  const districts = [{ id: 'nura', name: 'Нура' }, { id: 'esil', name: 'Есиль' }];
  const items = [
    { id: 1, title: 'Освещение у школы', summary: 'Заменены фонари во дворе.', districtId: 'nura', durationDays: 4, publishedAt: '2026-01-02T12:00:00Z', completedAt: '2026-01-01T12:00:00Z', residentConfirmed: true, source: 'real', before: [], after: [] },
    { id: 2, title: 'Новый детский сад', summary: 'Открыты новые группы.', districtId: 'esil', durationDays: 12, publishedAt: '2026-02-02T12:00:00Z', completedAt: '2026-02-01T12:00:00Z', residentConfirmed: false, source: 'demo', before: [], after: [] },
    { id: 3, title: 'Очищён двор', summary: 'Вывезен мусор.', districtId: 'nura', durationDays: 1, publishedAt: '2026-03-02T12:00:00Z', completedAt: '2026-03-01T12:00:00Z', residentConfirmed: true, source: 'real', before: [], after: [] },
  ];
  let failResults = false;
  await page.route('**/api/public/results', route => route.fulfill({ status: failResults ? 503 : 200, contentType: 'application/json', body: JSON.stringify(failResults ? { message: 'Unavailable' } : { items, districts }) }));
  await page.goto(origin + '/results.html?districtId=unknown');
  await page.waitForFunction(() => document.querySelectorAll('.result-card').length === 3);
  await visible('#filter-notice');
  assert.equal(new URL(page.url()).searchParams.has('districtId'), false);
  assert.equal(await page.locator('#stat-confirmed').innerText(), '2');
  await page.locator('#result-search').fill('очищен');
  assert.equal(await page.locator('.result-card').count(), 1, 'Search normalizes Russian ё');
  await page.locator('#reset-filters').click();
  await page.locator('#source-filter').selectOption('demo');
  assert.equal(await page.locator('.result-card h2').innerText(), 'Новый детский сад');
  await page.locator('#confirmation-filter').selectOption('confirmed');
  await visible('#results-empty');
  await page.locator('#clear-filter').click();
  await page.locator('#result-sort').selectOption('fastest');
  assert.equal(await page.locator('.result-card h2').first().innerText(), 'Очищён двор');
  await page.locator('#district-filter').selectOption('esil');
  await page.reload();
  await page.waitForFunction(() => document.querySelectorAll('.result-card').length === 1);
  assert.equal(await page.locator('#district-filter').inputValue(), 'esil');
  await page.locator('.result-details summary').click();
  assert.equal(await page.locator('.result-details').getAttribute('open'), '');
  await noOverflow();
  await page.screenshot({ path: '/tmp/ascension-results-navigation.png', fullPage: true });
  failResults = true;
  await page.locator('#refresh-results').click();
  await visible('#results-error');
  assert.equal(await page.locator('.result-card').count(), 0, 'A failed refresh must not retain potentially withdrawn publications');
  failResults = false;
  await page.locator('#retry-results').click();
  await page.waitForFunction(() => document.querySelectorAll('.result-card').length === 1);
  console.log('PASS results: search, 3 filters, sorting, URL reload, metrics, details, error retry, stale-data removal, mobile layout');

  const before = await context.request.get(origin + '/api/desk/complaints');
  const countBefore = (await before.json()).total;
  await page.goto(origin + '/demo.html');
  await visible('#demo-workspace');
  assert.equal(await page.locator('[data-step="4"]').isDisabled(), true);
  await page.locator('#demo-timer').click();
  await page.waitForFunction(() => document.getElementById('demo-clock').textContent !== '01:30');
  await page.locator('#demo-timer').click();
  assert.match(await page.locator('#demo-clock-hint').innerText(), /паузе/);
  await page.locator('#demo-next').click();
  await page.locator('[data-step="0"]').click();
  assert.equal(await page.locator('#demo-back').isDisabled(), true);
  await page.locator('[data-step="1"]').click();
  await page.locator('#demo-next').click();
  await page.locator('input[value=alternative]').check();
  await page.locator('#demo-next').click();
  assert.equal(await page.locator('#demo-next').isDisabled(), true);
  await page.locator('#demo-assign').click();
  await page.locator('#demo-next').click();
  await page.locator('[data-feedback=unresolved]').click();
  assert.equal(await page.locator('#demo-complete').isHidden(), true);
  assert.equal(await page.locator('#demo-comment').getAttribute('aria-invalid'), 'true');
  await page.locator('#demo-comment').fill('В нашем районе по-прежнему нет мест.');
  await page.locator('[data-feedback=unresolved]').click();
  await visible('#demo-complete');
  assert.match(await page.locator('#demo-complete-copy').innerText(), /повторная проверка/);
  await noOverflow();
  await page.screenshot({ path: '/tmp/ascension-demo-navigation.png', fullPage: true });
  await page.locator('[data-step="2"]').click();
  await page.locator('input[value=official]').check();
  assert.equal(await page.locator('[data-step="4"]').isDisabled(), true, 'Changing the decision invalidates its assignment and feedback');
  await page.locator('#demo-restart').click();
  assert.equal(await page.locator('#demo-clock').innerText(), '01:30');
  assert.equal(await page.locator('#demo-back').isDisabled(), true);
  assert.equal(await page.locator('[data-step="1"]').isDisabled(), true);
  const after = await context.request.get(origin + '/api/desk/complaints');
  assert.equal((await after.json()).total, countBefore, 'Demo must not create desk records');
  for (const path of ['/resident.html', '/results.html', '/demo.html']) {
    await page.setViewportSize({ width: 1440, height: 960 });
    await page.goto(origin + path);
    await noOverflow();
  }
  assert.deepEqual(errors, []);
  console.log('PASS demo: pauseable timer, stage navigation, decision invalidation, unresolved validation, completion, restart, no mutations, desktop/mobile layout');
} finally {
  await browser.close();
  const closed = new Promise(resolve => server.close(resolve));
  server.closeAllConnections();
  await closed;
  await rm(dir, { recursive: true, force: true });
}
