import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { once } from 'node:events';
import { backup, DatabaseSync } from 'node:sqlite';
import { createAppServer } from '../src/server.js';
import { openStore, passwordHash } from '../src/desk/store.js';
const scenario={decisions:[{measureId:'M7',districtId:'nura'},{measureId:'M8',districtId:'nura'},{measureId:'M10',districtId:'nura'},{measureId:'M12'},{measureId:'M5',districtId:'saryarka'}]};
async function fixture(t){
 const dir=await mkdtemp(join(tmpdir(),'desk-test-')),path=join(dir,'db.sqlite');let server;
 const db=openStore(path);db.prepare('INSERT INTO users VALUES(?,?,?)').run('operator',passwordHash('test-password-123'),'operator');db.close();
 async function start(){server=createAppServer({deskOptions:{path}});server.listen(0,'127.0.0.1');await once(server,'listening');}
 async function stop(){server.closeAllConnections();await new Promise(r=>server.close(r));}
 await start();t.after(async()=>{await stop();await rm(dir,{recursive:true,force:true});});
 let cookie='';
 async function call(route,body,method=body===undefined?'GET':'POST',headers={}){const res=await fetch(`http://127.0.0.1:${server.address().port}/api/desk/${route}`,{method,headers:{'Content-Type':'application/json','X-Desk-Request':'1',Cookie:cookie,...headers},body:body===undefined?undefined:JSON.stringify(body)});if(res.headers.get('set-cookie'))cookie=res.headers.get('set-cookie').split(';')[0];return {status:res.status, data:res.headers.get('content-type')?.includes('json')?await res.json():await res.arrayBuffer()};}
 return {call,path,dir,restart:async()=>{await stop();await start();}};
}
const complaint={submissionId:'one',text:'Не работает освещение <script>alert(1)</script>',districtId:'nura',category:'safety',address:'Тестовый адрес'};
async function login(f){assert.equal((await f.call('login',{login:'operator',password:'test-password-123'})).status,200);}
const edit=i=>({version:i.version,status:i.status,category:i.category,districtId:i.districtId,priority:i.priority,assignee:i.assignee});
test('desk authentication, CSRF, persistence, ownership boundary and logout',async t=>{const f=await fixture(t);assert.equal((await f.call('complaints')).status,401);assert.equal((await f.call('login',{login:'operator',password:'wrong'})).status,401);assert.equal((await f.call('login',{login:'operator',password:'test-password-123'},'POST',{'X-Desk-Request':'0'})).status,403);await login(f);assert.equal((await f.call('complaints',complaint,'POST',{Origin:'https://evil.test'})).status,403);const created=await f.call('complaints',complaint);assert.equal(created.status,201);assert.equal(created.data.source,'demo');await f.restart();assert.equal((await f.call(`complaints/${created.data.id}`)).data.text,complaint.text);assert.equal((await f.call('logout',{})).status,200);assert.equal((await f.call('complaints')).status,401);});
test('desk duplicate keys, filters, state machine and concurrent changes',async t=>{const f=await fixture(t);await login(f);let i=(await f.call('complaints',complaint)).data;assert.equal((await f.call('complaints',complaint)).status,200);assert.equal((await f.call('complaints',{...complaint,text:'changed'})).status,409);assert.equal((await f.call('complaints?q=освещение&districtId=nura')).data.total,1);assert.equal((await f.call('complaints?status=resolved')).data.total,0);assert.equal((await f.call(`complaints/${i.id}`,{...edit(i),status:'resolved',publicReply:'done'},'PATCH')).status,422);const old=edit(i);i=(await f.call(`complaints/${i.id}`,{...old,status:'review'},'PATCH')).data;assert.equal((await f.call(`complaints/${i.id}`,old,'PATCH')).status,409);i=(await f.call(`complaints/${i.id}`,{...edit(i),status:'work',assignee:'operator'},'PATCH')).data;assert.equal((await f.call(`complaints/${i.id}`,{...edit(i),status:'resolved'},'PATCH')).status,422);i=(await f.call(`complaints/${i.id}`,{...edit(i),status:'resolved',publicReply:'Освещение восстановлено (демо)'},'PATCH')).data;assert.equal(i.replies[0].delivery,'not_connected');assert.equal(i.history.length,4);});
test('desk attachments require valid image and authentication; scenarios are recalculated; backup restores records',async t=>{const f=await fixture(t);await login(f);const i=(await f.call('complaints',complaint)).data;assert.equal((await f.call(`complaints/${i.id}/attachments`,{name:'bad.png',mime:'image/png',base64:Buffer.from('not image').toString('base64')})).status,422);const file=await f.call(`complaints/${i.id}/attachments`,{name:'pixel.png',mime:'image/png',base64:'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aXioAAAAASUVORK5CYII='});assert.equal(file.status,201);const attachment=file.data.attachments[0];assert.equal((await f.call(`attachments/${attachment.id}`)).status,200);const saved=await f.call('scenarios',{name:'Official',scenario,complaintId:i.id,result:{score:999}});assert.equal(saved.status,201);assert.ok(Math.abs(saved.data.result.score-56.54307)<1e-8);assert.equal((await f.call('scenarios',{name:'bad',scenario:{decisions:[]}})).status,422);await f.restart();assert.equal((await f.call('scenarios')).data.length,1);const source=new DatabaseSync(f.path),copy=join(f.dir,'restore.sqlite');await backup(source,copy);source.close();const restored=new DatabaseSync(copy);assert.equal(restored.prepare('PRAGMA integrity_check').get().integrity_check,'ok');assert.equal(restored.prepare('SELECT count(*) AS n FROM complaints').get().n,1);assert.equal(restored.prepare('SELECT count(*) AS n FROM attachments').get().n,1);restored.close();await f.call('logout',{});assert.equal((await f.call(`attachments/${attachment.id}`)).status,401);});
